include: package:very_good_analysis/analysis_options.2.4.0.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart" 
    - "lib/places/helper/calculate_distance.dart" 
linter:
  rules:
    public_member_api_docs: false

