name: find_me_food_bloc
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  flutter_bloc: ^8.0.0
  bloc: ^8.0.1
  equatable: ^2.0.3
  freezed_annotation: ^1.1.0
  intl: ^0.17.0
  hydrated_bloc: ^8.0.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.3
  flutter_services_binding: ^0.1.0

  location_repository:
    path: packages/location_repository
  nearby_places_repository:
    path: packages/nearby_places_repository    


dev_dependencies:
  bloc_test: ^9.0.1
  build_runner: 
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.3
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
