name: nearby_places_repository
description: A dart repository for fetching nearby locations.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0 <3.0.0'


dependencies:
  path: ^1.8.0
  json_annotation: ^4.0.1
  sqflite: ^2.0.2
  freezed_annotation:
  google_places_api:
    path: ../google_places_api

dev_dependencies:
  flutter_lints: ^1.0.0
  build_runner:
  json_serializable: ^4.1.4
  freezed:
  mocktail: ^0.2.0
  test: ^1.16.4
  very_good_analysis: ^2.4.0